export const vehicles =[
  {
    make: "Toyota",
    model: "HiLux SR5",
    year: 2024,
    price: 72990.00,
    bodyType: "UTE",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 10.2,
    fuelConsumptionExtraUrban: 7.3,
    fuelConsumptionCombined: 8.4,
    engineCapacity: 2.8,
    cylinders: 4,
    odometer: 45,
    driveType: "4WD",
    doors: 4,
    seats: 5,
    color: "Glacier White",
    rego: "ABC123",
    vin: "MR0BA3CD601234567",
    stockNumber: "TY24HIL001",
    images: [
      "https://www.toyota.com.au/-/media/toyota/main-site/vehicle-hubs/hilux/bep/2024/hilux_range_sr5_v2.jpg?rev=7658406e952f4c178dfaba44fdc67769",
"https://cdn.yeecar.com.au/uploads/car/spec/S000EIIZ.jpg",
"https://nextgen-images.cdn.dealersolutions.com.au/modular.multisite.dealer.solutions/wp-content/uploads/2018/02/28105456/White-1.png?format=webp&width=1193" 
    ],
    description: "This 2024 Toyota HiLux SR5 is the ultimate workhorse with premium features. Featuring a powerful 2.8L turbo diesel engine producing 150kW and 500Nm of torque. Perfect for both work and weekend adventures with its comfortable interior and proven reliability.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Satellite Navigation", "Reverse Camera", "Leather Seats", "Cruise Control", "Bluetooth", "Alloy Wheels", "Tow Bar", "Apple CarPlay", "Android Auto"],
    viewsCount: 127,
    createdAt: new Date("2024-01-15T10:30:00Z"),
    updatedAt: new Date("2024-01-15T10:30:00Z")
  },
  {
    make: "Ford",
    model: "Ranger Sport 3.0",
    year: 2024,
    price: 78990.00,
    bodyType: "UTE",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 10.5,
    fuelConsumptionExtraUrban: 7.1,
    fuelConsumptionCombined: 8.4,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 32,
    driveType: "4WD",
    doors: 4,
    seats: 5,
    color: "Arctic White",
    rego: "DEF456",
    vin: "M6GMFC90W6789012",
    stockNumber: "FD24RNG002",
    images: [
      "https://www.gpas-cache.ford.com/guid/0db6dd55-ac01-3102-af23-622f14054896.png",
"https://cdn.images.stock.i-motor.net.au/vehicles/medium/3124083-J22M-52874096-7c46-5d82-bd75-ea4d75056f19.jpg",
"https://cdn.images.stock.i-motor.net.au/vehicles/medium/3124083-J22M-87bea07d-be35-55b8-bbaa-ab2dd6a82c74.jpg"

    ],
    description: "This 2024 Ford Ranger Sport 3.0 features a powerful V6 diesel engine delivering 184kW and 600Nm of torque. Upgraded with the latest tech including a 12-inch touchscreen and advanced driver assistance. Exceptional towing capacity with premium comfort for all passengers.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["V6 Diesel", "10-Speed Auto", "12-inch Touchscreen", "Adaptive Cruise Control", "Leather Trim", "360° Camera", "Wireless Charging", "Apple CarPlay", "Android Auto"],
    viewsCount: 156,
    createdAt: new Date("2024-02-20T14:45:00Z"),
    updatedAt: new Date("2024-02-20T14:45:00Z")
  },
  {
    make: "Mazda",
    model: "CX-5 G25 Akera",
    year: 2024,
    price: 54990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.5,
    fuelConsumptionExtraUrban: 6.4,
    fuelConsumptionCombined: 7.5,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 78,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Soul Red Crystal",
    rego: "GHI789",
    vin: "JM0KF4WLA00678912",
    stockNumber: "MZ24CX5003",
    images: [
"https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/mazda/cx-5/2024/50695502-8420-5f43-8a13-236147050000",
"https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/vbx61hnwzkqwewmflsnr",
"https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/mazda/cx-5/2024/9b4cd0bb-6421-55af-bf16-8ce4e4350000"


    ],
    description: "Top-of-the-range Mazda CX-5 G25 Akera with all the luxury features you desire. This refined SUV offers 140kW of power with sophisticated handling and Mazda's signature driving dynamics. Premium Nappa leather interior with advanced safety features make this the perfect family vehicle.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Nappa Leather", "Bose Sound System", "Sunroof", "Heated & Ventilated Seats", "360° View Monitor", "Radar Cruise Control", "Heads-up Display", "Wireless Apple CarPlay", "Android Auto"],
    viewsCount: 94,
    createdAt: new Date("2024-03-05T09:15:00Z"),
    updatedAt: new Date("2024-03-05T09:15:00Z")
  },
  {
    make: "Hyundai",
    model: "i30 N Line",
    year: 2024,
    price: 38990.00,
    bodyType: "HATCHBACK",
    transmission: "DCT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.2,
    fuelConsumptionExtraUrban: 5.6,
    fuelConsumptionCombined: 6.8,
    engineCapacity: 1.5,
    cylinders: 4,
    odometer: 15,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Performance Blue",
    rego: "JKL012",
    vin: "KMHH351CBNU123456",
    stockNumber: "HY24I30004",
    images: [
      "https://www.hyundai.com/content/dam/hyundai/au/en/models/i30-n/2025/HeroCarousel_i30_N_MY25_950x415.png",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7F_awBBAVeuB-9UQXc4WP_oAkEyCSdYDbAB78fXXqc9DF7XzzHmsorOHrX_CXwkDRuv0&usqp=CAU",
      "https://editorial.pxcrush.net/carsales/general/editorial/2024-hyundai-i30-sedan-n-65.jpg?width=1024&height=682"
    ],
    description: "This sporty 2024 Hyundai i30 N Line features a turbocharged 1.5L engine paired with a quick-shifting 7-speed DCT. Designed with performance styling and enhanced handling characteristics for an engaging driving experience. Packed with tech and safety features for daily practicality.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Sports Body Kit", "LED Headlights", "10.25\" Touchscreen", "Paddle Shifters", "Wireless Charging", "Blind Spot Monitoring", "Sports Seats", "Apple CarPlay", "Android Auto"],
    viewsCount: 78,
    createdAt: new Date("2024-03-18T16:20:00Z"),
    updatedAt: new Date("2024-03-18T16:20:00Z")
  },
  {
    make: "Toyota",
    model: "Corolla ZR Hybrid",
    year: 2023,
    price: 32990.00,
    bodyType: "HATCHBACK",
    transmission: "CVT",
    fuelType: "HYBRID",
    fuelConsumptionUrban: 3.5,
    fuelConsumptionExtraUrban: 3.8,
    fuelConsumptionCombined: 3.6,
    engineCapacity: 1.8,
    cylinders: 4,
    odometer: 12450,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Frosted White",
    rego: "MNO345",
    vin: "JTDBR9HE2NJ567890",
    stockNumber: "TY23COR005",
    images: [
      "https://drivingenthusiast.com.au/wp-content/uploads/2023/04/2023-Toyota-Corolla-ZR-Hybrid-doors.jpg",
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/toyota/corolla/2023/13a16d07-15a2-5a19-b1ca-3deff0f50000",
      "https://nextgen-images.cdn.dealersolutions.com.au/modular.multisite.dealer.solutions/wp-content/uploads/sites/1576/2022/11/09183110/64267_hr-scaled.jpg?format=webp&width=2560"
    ],
    description: "This near-new Toyota Corolla ZR Hybrid combines exceptional fuel economy with premium features. Top-spec model with leather accented interior, JBL premium audio, and head-up display. Toyota's renowned hybrid technology delivers smooth, efficient performance with just 12,450km on the odometer.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["JBL Premium Audio", "Head-Up Display", "Heated Seats", "Wireless Charging", "Adaptive LED Headlights", "Panoramic View Monitor", "Dual-Zone Climate", "Apple CarPlay", "Android Auto"],
    viewsCount: 112,
    createdAt: new Date("2024-04-02T11:30:00Z"),
    updatedAt: new Date("2024-04-02T11:30:00Z")
  },
  {
    make: "BMW",
    model: "3 Series 330i M Sport",
    year: 2022,
    price: 64990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.7,
    fuelConsumptionExtraUrban: 5.4,
    fuelConsumptionCombined: 6.6,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 24680,
    driveType: "RWD",
    doors: 4,
    seats: 5,
    color: "Mineral Grey",
    rego: "PQR678",
    vin: "WBA5R1C09MCF12345",
    stockNumber: "BM22330006",
    images: [
      "https://carsales.pxcrush.net/carsales/cars/dealer/1b2f3o9zlubx2532ypbn8elvu.jpg?pxc_method=fitfill&pxc_bgtype=self&pxc_size=720,480",
      "https://edge.pxcrush.net/cars/dealer/ddtdlh4gee3a6k85p2f6f6nnq.jpg?pxc_expires=20250807121833&pxc_clear=1&pxc_signature=f969631671f23a8f4e78c823427b64dc&pxc_size=1795%2C1347&pxc_method=fit",
      "https://dealersolutions.b-cdn.net/20241217/80773166a6918eb0e7371ba58909d49c.jpg"
    ],
    description: "This immaculate BMW 330i M Sport showcases German engineering excellence with its 2.0L turbocharged engine. Luxurious interior with premium leather, advanced driver assistance systems, and the latest iDrive infotainment. One owner vehicle with full service history and the balance of factory warranty.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["M Sport Package", "Harman/Kardon Sound", "Digital Dashboard", "Heated Sports Seats", "Adaptive LED Headlights", "Driving Assistant Professional", "Electric Sunroof", "Wireless Apple CarPlay", "Android Auto"],
    viewsCount: 186,
    createdAt: new Date("2024-04-25T13:45:00Z"),
    updatedAt: new Date("2024-04-25T13:45:00Z")
  },
  {
    make: "Kia",
    model: "Sorento GT-Line Diesel",
    year: 2023,
    price: 59990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 8.0,
    fuelConsumptionExtraUrban: 5.8,
    fuelConsumptionCombined: 6.6,
    engineCapacity: 2.2,
    cylinders: 4,
    odometer: 19540,
    driveType: "AWD",
    doors: 5,
    seats: 7,
    color: "Gravity Blue",
    rego: "STU901",
    vin: "KNART813BN5789012",
    stockNumber: "KI23SOR007",
    images: [
      "https://voom.com.au/wp-content/uploads/vehicle-images/KIA/SORENTO/2023/5OD-4.JPG",
      "https://www.chasingcars.com.au/wp-content/uploads/2022/08/ezgif.com-gif-maker-3-copy-2.jpg",
      "https://editorial.pxcrush.net/carsales/general/editorial/kia-sorento-gt-line-hev-awd-20-ly8f.jpg?width=1024&height=682"
    ],
    description: "This top-of-the-range Kia Sorento GT-Line offers luxury and practicality for the modern family. Seven genuine seats with leather trim and a powerful yet efficient 2.2L turbo diesel engine. Loaded with technology including a 360° camera system and premium Bose audio.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Bose Premium Sound", "7 Seats", "360° Camera", "Quilted Nappa Leather", "Panoramic Sunroof", "Heated & Ventilated Seats", "Remote Smart Parking Assist", "Apple CarPlay", "Android Auto"],
    viewsCount: 143,
    createdAt: new Date("2024-05-10T15:30:00Z"),
    updatedAt: new Date("2024-05-10T15:30:00Z")
  },
  {
    make: "Volkswagen",
    model: "Golf GTI",
    year: 2022,
    price: 49990.00,
    bodyType: "HATCHBACK",
    transmission: "DCT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.9,
    fuelConsumptionExtraUrban: 5.4,
    fuelConsumptionCombined: 6.8,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 26780,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Kings Red",
    rego: "VWX234",
    vin: "WVWZZZCDZNT234567",
    stockNumber: "VW22GTI008",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHufuThdEnGtL-5c9g1TbnP-fA7gAskG5nTQ&s",
      "https://images.cars.com/cldstatic/wp-content/uploads/volkswagen-golf-gti-2022-01-exterior--front--red.jpg",
      "https://images.hgmsites.net/hug/2022-volkswagen-golf-gti_100793886_h.jpg"
    ],
    description: "This Volkswagen Golf GTI delivers the perfect blend of performance and everyday practicality. The 2.0L turbocharged engine produces 180kW with razor-sharp handling through its adaptive chassis control. Premium interior with tartan cloth sports seats and the latest infotainment system.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Digital Cockpit Pro", "Harman/Kardon Sound", "Adaptive Chassis Control", "Sports Seats", "Matrix LED Headlights", "Panoramic Sunroof", "7-Speed DSG", "Wireless Apple CarPlay", "Android Auto"],
    viewsCount: 201,
    createdAt: new Date("2024-05-28T10:15:00Z"),
    updatedAt: new Date("2024-05-28T10:15:00Z")
  },
  {
    make: "Mercedes-Benz",
    model: "C200 AMG Line",
    year: 2021,
    price: 59990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.6,
    fuelConsumptionExtraUrban: 5.3,
    fuelConsumptionCombined: 6.5,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 32450,
    driveType: "RWD",
    doors: 4,
    seats: 5,
    color: "Obsidian Black",
    rego: "YZA567",
    vin: "WDDWF4CB0MA345678",
    stockNumber: "MB21C20009",
    images: [
      "https://online.mbberwick.com.au/_next/image?url=https%3A%2F%2Fnextgen-cella.cdn.dealersolutions.com.au%2F20241017%2F7c761b9f2ef8be680161cfeb08fba2c4.jpg&w=3840&q=75",
      "https://i.ytimg.com/vi/P7qBrZ9O2wk/sddefault.jpg",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_810,w_1215,f_auto,t_cg_base/v1/editorial/2023-Mercedes-benz-C-Class-C200-sedan-blue-Glen-Sullivan-1200x800p-(11).jpg"
    ],
    description: "This Mercedes-Benz C200 AMG Line exemplifies luxury motoring with its sleek design and premium materials. Featuring innovative MBUX infotainment with augmented reality navigation and 64-color ambient lighting. One local owner with full service history through Mercedes-Benz authorized dealerships.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["AMG Line Package", "Burmester Surround Sound", "Panoramic Sunroof", "Heated Electric Seats", "LED Headlights", "MBUX Navigation", "Wireless Charging", "Apple CarPlay", "Android Auto"],
    viewsCount: 168,
    createdAt: new Date("2024-06-15T14:20:00Z"),
    updatedAt: new Date("2024-06-15T14:20:00Z")
  },
  {
    make: "Subaru",
    model: "Forester 2.5i-S",
    year: 2023,
    price: 44990.00,
    bodyType: "SUV",
    transmission: "CVT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.2,
    fuelConsumptionExtraUrban: 6.4,
    fuelConsumptionCombined: 7.4,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 15420,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Horizon Blue",
    rego: "BCD890",
    vin: "JF2SJAWC2NH678901",
    stockNumber: "SB23FOR010",
    images: [
      "https://media.whichcar.com.au/uploads/2023/05/61e3aae5-2023-subaru-outback-awd-touring-xt-50-year-edition.jpg",
      "https://images.carexpert.com.au/resize/800/-/cms/v1/media/2023-subaru-forester-primary-image.jpg",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/cwqejhpn2u6il1xubzug"
    ],
    description: "This Subaru Forester 2.5i-S offers renowned symmetrical all-wheel drive with X-Mode for all-terrain capability. The top-spec model includes leather seats, an electric sunroof, and Subaru's EyeSight driver assist technology. Perfect for adventurous families with its combination of comfort, safety, and capability.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Symmetrical AWD", "X-Mode", "EyeSight Driver Assist", "Electric Sunroof", "Leather Interior", "Power Tailgate", "Harman/Kardon Audio", "Apple CarPlay", "Android Auto"],
    viewsCount: 127,
    createdAt: new Date("2024-07-01T09:45:00Z"),
    updatedAt: new Date("2024-07-01T09:45:00Z")
  },
  {
    make: "Nissan",
    model: "X-Trail ST-L",
    year: 2022,
    price: 37990.00,
    bodyType: "SUV",
    transmission: "CVT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.1,
    fuelConsumptionExtraUrban: 6.7,
    fuelConsumptionCombined: 7.6,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 28760,
    driveType: "AWD",
    doors: 5,
    seats: 7,
    color: "Diamond Black",
    rego: "EFG123",
    vin: "JNKRJ15Y3N6789012",
    stockNumber: "NI22XTR011",
    images: [
      "https://carsales.pxcrush.net/carsales/car/dealer/9sy55qox81xb08yzxeps0x847.jpg?pxc_method=fitfill&pxc_bgtype=self&pxc_size=720,480",
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/nissan/x-trail/2023/782ee32f-4ec8-54e9-8b1f-fa5850450000",
      "https://editorial.pxcrush.net/carsales/general/editorial/2022-nissan-x-trail-st-plus-2wd-10.jpg?width=1024&height=682"
    ],
    description: "This versatile Nissan X-Trail ST-L offers seven-seat flexibility with intelligent all-wheel drive capability. Perfect for family adventures with a panoramic sunroof and advanced safety features including ProPILOT assist. Excellent condition with service history and the balance of Nissan's factory warranty.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["7 Seats", "Panoramic Sunroof", "ProPILOT Assist", "Leather-Accented Seats", "Around View Monitor", "Motion-Activated Tailgate", "Dual-Zone Climate", "Apple CarPlay", "Android Auto"],
    viewsCount: 105,
    createdAt: new Date("2024-07-20T16:30:00Z"),
    updatedAt: new Date("2024-07-20T16:30:00Z")
  },
  {
    make: "Honda",
    model: "Civic VTi-LX",
    year: 2021,
    price: 32990.00,
    bodyType: "SEDAN",
    transmission: "CVT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 7.9,
    fuelConsumptionExtraUrban: 5.3,
    fuelConsumptionCombined: 6.3,
    engineCapacity: 1.5,
    cylinders: 4,
    odometer: 34670,
    driveType: "FWD",
    doors: 4,
    seats: 5,
    color: "Platinum White",
    rego: "HIJ456",
    vin: "SHHFK4850MU901234",
    stockNumber: "HO21CIV012",
    images: [
      "https://vehicle-cdn.autoleague.cloud/_next/image/?url=https://vehicle-cdn.autoleague.cloud/30641_U508412_1.jpg&w=3840&q=90",
      "https://media.whichcar.com.au/uploads/2025/02/dd32efa2-Honda_Civic_VTi-LX_panning_side_profile_left-scaled.jpg",
      "https://media.whichcar.com.au/uploads/2025/02/fbb00a85-Honda_Civic_VTi-LX_interior_driver_s_side-scaled.jpg"
    ],
    description: "This premium Honda Civic VTi-LX features a responsive 1.5L turbocharged engine with excellent fuel efficiency. As the top-of-the-range model, it includes leather seats, a power sunroof, and Honda's full suite of Honda Sensing safety technologies. One owner vehicle with complete service history.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Leather Seats", "Power Sunroof", "Honda Sensing Suite", "Digital Instrument Display", "Premium Audio System", "Wireless Phone Charging", "LED Headlights", "Apple CarPlay", "Android Auto"],
    viewsCount: 92,
    createdAt: new Date("2024-08-05T11:15:00Z"),
    updatedAt: new Date("2024-08-05T11:15:00Z")
  },
  {
    make: "Audi",
    model: "Q5 45 TFSI quattro",
    year: 2023,
    price: 79990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.8,
    fuelConsumptionExtraUrban: 6.9,
    fuelConsumptionCombined: 7.9,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 14320,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Glacier White",
    rego: "KLM789",
    vin: "WAUZZZFY5PA123456",
    stockNumber: "AU23Q45013",
    images: [
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:1280:720:1/driveau/upload/vehicles/used/audi/q5/2023/c52b103e-7531-5429-8d47-b07730a50000",
      "https://images.carexpert.com.au/resize/700/-/vehicles/source-g/2/c/2c40b70e.jpg",
      "https://cdn.yeecar.com.au/uploads/20230613/aac4e1fd921446a78c185b094d10e7cb.jpg"
    ],
    description: "This Certified Pre-Owned Audi Q5 45 TFSI quattro offers premium luxury with Audi's renowned quattro all-wheel drive system. The powerful 2.0L turbocharged engine delivers 183kW with mild hybrid efficiency. Includes Audi's comprehensive certified pre-owned warranty for peace of mind.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["S line Sport Package", "Matrix LED Headlights", "Bang & Olufsen 3D Sound", "Virtual Cockpit", "Adaptive Cruise Control", "Panoramic Sunroof", "Heated & Ventilated Seats", "Wireless Apple CarPlay", "Android Auto"],
    viewsCount: 178,
    createdAt: new Date("2024-08-25T13:30:00Z"),
    updatedAt: new Date("2024-08-25T13:30:00Z")
  },
  {
    make: "Tesla",
    model: "Model 3 Long Range",
    year: 2022,
    price: 64990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 21450,
    driveType: "AWD",
    doors: 4,
    seats: 5,
    color: "Deep Blue Metallic",
    rego: "NOP012",
    vin: "5YJ3E1EAXNF234567",
    stockNumber: "TS22ML3014",
    images: [
      "https://virtualyard.com.au/photos/OxZwGOAvLj9UvhzofkOTcnK8bHg4GvwOhMktsuTA0K49FtL7qjmB58U2hbUVx13cmjvPBdUJxrOum76U6EL0vgs80N3HA4agQZrScsj5Y64.jpg",
      "https://storage.googleapis.com/au-assets/zdfzF3G2ym34eLIj6diF7qXgvVwhcAXVndnWiEteDN7uOgeM_i-E3VJEp2SXtakuAcb5yEBTkVMv4mX5S_mavmWYTiVCM3hBsassWWwduSSRKtlW_x4dG68pHtn85JJN.webp",
      "https://virtualyard.com.au/photos/KnlgiHThCRo4MKCVyzxfv37LZfD3lEAxtGB9ShNGJW6k62IhxtuLRVWtduLsfq6kkk1lOwwhkPRLYC4tXl72yyMnExZIDJP0ly9ylSRQpRg.jpg"
    ],
    description: "This Certified Pre-Owned Tesla Model 3 Long Range offers impressive 614km range with dual motor all-wheel drive. Lightning-fast acceleration with 0-100 km/h in just 4.4 seconds and Tesla's renowned Autopilot capability. Includes Tesla's comprehensive certified pre-owned inspection and warranty.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Autopilot", "Premium Interior", "Glass Roof", "15\" Touchscreen", "Premium Audio", "Heated Seats", "Wireless Charging", "Over-the-air Updates", "Sentry Mode"],
    viewsCount: 243,
    createdAt: new Date("2024-09-10T15:45:00Z"),
    updatedAt: new Date("2024-09-10T15:45:00Z")
  },
  {
    make: "Mitsubishi",
    model: "Outlander Exceed",
    year: 2023,
    price: 47990.00,
    bodyType: "SUV",
    transmission: "CVT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.0,
    fuelConsumptionExtraUrban: 6.8,
    fuelConsumptionCombined: 7.6,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 16780,
    driveType: "AWD",
    doors: 5,
    seats: 7,
    color: "White Diamond",
    rego: "QRS345",
    vin: "JA4ATCAU7PZ345678",
    stockNumber: "MI23OUT015",
    images: [
      "https://resource.digitaldealer.com.au/image/57935342367f475e256a6f513745144_0_0.jpg",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_810,w_1215,f_auto,t_cg_base/v1/editorial/2023-mitsubishi-outlander-phev-exceed-tourer-suv-white-marcus-craft-1200x800-(2).jpg",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/1b3f4849-b5b9-5482-a4e1-778790850000"
    ],
    description: "This Certified Pre-Owned Mitsubishi Outlander Exceed offers luxury and versatility with genuine 7-seat capacity. The top-spec model includes quilted leather seats, panoramic sunroof, and Mitsubishi's advanced S-AWC all-wheel drive system. Backed by Mitsubishi's Diamond Advantage 10-year warranty program.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["7 Seats", "Quilted Leather", "Panoramic Sunroof", "BOSE Premium Sound", "Head-Up Display", "MI-PILOT Assist", "Power Tailgate", "Apple CarPlay", "Android Auto"],
    viewsCount: 132,
    createdAt: new Date("2024-09-28T10:30:00Z"),
    updatedAt: new Date("2024-09-28T10:30:00Z")
  },
  {
    make: "Lexus",
    model: "NX 350h F Sport",
    year: 2022,
    price: 72990.00,
    bodyType: "SUV",
    transmission: "CVT",
    fuelType: "HYBRID",
    fuelConsumptionUrban: 5.2,
    fuelConsumptionExtraUrban: 4.8,
    fuelConsumptionCombined: 5.0,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 18950,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Sonic Chrome",
    rego: "TUV678",
    vin: "JTJDARDZ0N2456789",
    stockNumber: "LX22NX3016",
    images: [
      "https://carsguide-res.cloudinary.com/image/upload/e_trim:10,f_auto/c_scale,t_cg_base,w_678/v1/editorial/vhs/lexus-nx-350.png",
      "https://editorial.pxcrush.net/carsales/general/editorial/2022_lexus_nx_350h_sports-luxury_1022.jpg?width=1024&height=682",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoDtUNgW6JwndAVYCI2QtdC-ETI0mdnZabUQ&s"
    ],
    description: "This Certified Pre-Owned Lexus NX 350h F Sport combines luxury with efficiency through its sophisticated hybrid powertrain. Featuring F Sport enhancements including adaptive variable suspension and unique styling elements. Thoroughly inspected with comprehensive Lexus certification and extended warranty coverage.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["F Sport Package", "Mark Levinson Audio", "14-inch Touchscreen", "Head-Up Display", "360° Panoramic View", "Heated & Ventilated Seats", "Wireless Charging", "Apple CarPlay", "Android Auto"],
    viewsCount: 156,
    createdAt: new Date("2024-10-15T14:15:00Z"),
    updatedAt: new Date("2024-10-15T14:15:00Z")
  },
  {
    make: "Mazda",
    model: "MX-5 GT RS",
    year: 2021,
    price: 42990.00,
    bodyType: "CONVERTIBLE",
    transmission: "MANUAL",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.8,
    fuelConsumptionExtraUrban: 5.8,
    fuelConsumptionCombined: 6.9,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 24680,
    driveType: "RWD",
    doors: 2,
    seats: 2,
    color: "Soul Red Crystal",
    rego: "WXY901",
    vin: "JM1NDAC77M0567890",
    stockNumber: "MZ21MX5017",
    images: [
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/mazda/mx-5/2021/5a6a5276-67a8-5e38-b37a-8f3cba150000",
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/mazda/mx-5/2021/d3b19c72-292b-52cc-8f9f-6e4f2b950000",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2024-Mazda-MX-5-RF-GT-Convertible-Red-1200x800-(11).jpg"
    ],
    description: "This rare Mazda MX-5 GT RS is the ultimate expression of the world's best-selling roadster. Enhanced with Brembo brakes, BBS forged wheels, and Recaro sports seats for the driving enthusiast. Pristine condition with full service history and low kilometers for a truly collectible modern classic.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Brembo Brakes", "BBS Forged Wheels", "Recaro Seats", "Bilstein Dampers", "Limited Slip Differential", "Apple CarPlay", "Android Auto", "Bose Sound System", "Soft-top Convertible"],
    viewsCount: 198,
    createdAt: new Date("2024-11-01T09:30:00Z"),
    updatedAt: new Date("2024-11-01T09:30:00Z")
  },
  {
    make: "Toyota",
    model: "RAV4 Cruiser Hybrid",
    year: 2023,
    price: 49990.00,
    bodyType: "SUV",
    transmission: "CVT",
    fuelType: "HYBRID",
    fuelConsumptionUrban: 4.7,
    fuelConsumptionExtraUrban: 4.8,
    fuelConsumptionCombined: 4.7,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 19430,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Graphite",
    rego: "ZAB234",
    vin: "JTMWWREV10D678901",
    stockNumber: "TY23RAV018",
    images: [
      "https://nextgen-cella.cdn.dealersolutions.com.au/20241223/6007ed2762dae66476c4b4ae209517f7.3.jpg",
      "https://images.carexpert.com.au/crop/1200/630/cms/v1/media/2023-12-231124toyota-rav4-xse-hybridstill-6.jpg",
      "https://editorial.pxcrush.net/carsales/general/editorial/2024-toyota-rav4-edge-hybrid-15.jpg?width=1024&height=682"
    ],
    description: "This Toyota RAV4 Cruiser Hybrid offers exceptional efficiency with AWD capability and premium features. The sophisticated hybrid system delivers 163kW with remarkable fuel economy of just 4.7L/100km. Premium features include leather accented interior and panoramic view monitor for easy parking.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["AWD Hybrid System", "Leather Interior", "JBL Premium Audio", "Panoramic View Monitor", "Power Tailgate", "Wireless Charging", "Heated & Ventilated Seats", "Apple CarPlay", "Android Auto"],
    viewsCount: 146,
    createdAt: new Date("2024-11-20T16:45:00Z"),
    updatedAt: new Date("2024-11-20T16:45:00Z")
  },
  {
    make: "Hyundai",
    model: "Tucson Elite N Line",
    year: 2022,
    price: 41990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.6,
    fuelConsumptionExtraUrban: 6.5,
    fuelConsumptionCombined: 7.7,
    engineCapacity: 1.6,
    cylinders: 4,
    odometer: 27860,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Shadow Grey",
    rego: "CDE567",
    vin: "TMAJ38A67NJ789012",
    stockNumber: "HY22TUC019",
    images: [
      "https://carsales.pxcrush.net/carsales/car/cil/4ndlgfsg315u6jxe4n1bctsn2.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900,600",
      "https://d2s8i866417m9.cloudfront.net/photo/7386198/photo/medium-d36acacbda9046b5b44e2c507aeca5be.jpg",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/oswrlehrc6cjuzidopiv"
    ],
    description: "This Hyundai Tucson Elite N Line combines distinctive sporty styling with practical SUV versatility. The turbocharged 1.6L engine delivers 132kW through a responsive 7-speed DCT transmission. Features N Line exterior and interior styling with all-wheel drive capability for all-weather confidence.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["N Line Sports Package", "Leather Interior", "Panoramic Sunroof", "Bose Premium Audio", "10.25\" Touchscreen", "Heated & Ventilated Seats", "Blind-Spot View Monitor", "Apple CarPlay", "Android Auto"],
    viewsCount: 124,
    createdAt: new Date("2024-12-05T11:30:00Z"),
    updatedAt: new Date("2024-12-05T11:30:00Z")
  },
  {
    make: "Ford",
    model: "Mustang GT",
    year: 2021,
    price: 64990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 16.5,
    fuelConsumptionExtraUrban: 8.2,
    fuelConsumptionCombined: 11.3,
    engineCapacity: 5.0,
    cylinders: 8,
    odometer: 22670,
    driveType: "RWD",
    doors: 2,
    seats: 4,
    color: "Antimatter Blue",
    rego: "FGH890",
    vin: "1FA6P8CF0M5890123",
    stockNumber: "FD21MGT020",
    images: [
      "https://editorial.pxcrush.net/carsales/general/editorial/2021_ford_mustang_mach_1_dynamic_v1_current.jpg?width=1024&height=682",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/fab3zkakp8krismdg55u",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2021-Ford-Mustang-GT-auto=green-coupe-peter-anderson-1200x800-(12).jpg"
    ],
    description: "This Ford Mustang GT delivers exhilarating performance with its 5.0L V8 engine producing 339kW of power. The 10-speed automatic transmission offers lightning-fast shifts with multiple drive modes. Premium features include leather interior, B&O premium sound system, and active valve exhaust.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["5.0L V8 Engine", "10-Speed Auto", "Leather Interior", "Bang & Olufsen Sound", "Digital Instrument Cluster", "Active Exhaust", "Performance Package", "Apple CarPlay", "Android Auto"],
    viewsCount: 267,
    createdAt: new Date("2024-12-25T13:15:00Z"),
    updatedAt: new Date("2024-12-25T13:15:00Z")
  },
  {
    make: "Toyota",
    model: "LandCruiser 300 Series",
    year: 2024,
    price: 137990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 11.5,
    fuelConsumptionExtraUrban: 8.2,
    fuelConsumptionCombined: 9.5,
    engineCapacity: 3.3,
    cylinders: 6,
    odometer: 0,
    driveType: "4WD",
    doors: 5,
    seats: 7,
    color: "Pearl White",
    rego: "XYZ789",
    vin: "JTMCY7AJ0P4123456",
    stockNumber: "TY24LC30021",
    images: [
      "https://cdn.rotorint.com/LandCruiser_300/2021_07_Jul/e/360/png/lo/940x529/SPN_LC3_010070FB205E55200B0_comp_015.png",
      "https://images.autodaily.com.au/2021/06/New-Toyota-Land-Cruiser-4.jpg",
      "https://www.merimbulanewsweekly.com.au/images/transform/v1/crop/frm/silverstone-feed-data/125d46ca-0b7f-4b12-8315-fce0fb2c3233.jpg/r0_0_800_533_w800_h533_fmax.jpg"
    ],
    description: "The all-new Toyota LandCruiser 300 Series represents the pinnacle of Toyota's off-road capability. Featuring a powerful 3.3L twin-turbo diesel V6 engine producing 227kW and 700Nm of torque. Premium interior with advanced technology and unmatched off-road capability.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Multi-Terrain Select", "Crawl Control", "KDSS Suspension", "Premium Leather", "14-inch Touchscreen", "JBL Premium Audio", "Panoramic View Monitor", "Apple CarPlay", "Android Auto"],
    viewsCount: 289,
    createdAt: new Date("2024-01-05T09:30:00Z"),
    updatedAt: new Date("2024-01-05T09:30:00Z")
  },
  {
    make: "Isuzu",
    model: "D-MAX X-Terrain",
    year: 2024,
    price: 72990.00,
    bodyType: "UTE",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 9.8,
    fuelConsumptionExtraUrban: 7.2,
    fuelConsumptionCombined: 8.2,
    engineCapacity: 3.0,
    cylinders: 4,
    odometer: 0,
    driveType: "4WD",
    doors: 4,
    seats: 5,
    color: "Obsidian Grey",
    rego: "ISU123",
    vin: "MPATFS47JND123456",
    stockNumber: "IS24DMX022",
    images: [
      "https://carsales.pxcrush.net/carsales/car/cil/w3qvs8sl5a1wmdegtk1v7zm2d.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900,600",
      "https://cdn.24h.com.vn/upload/4-2024/images/2024-12-01/i--5--1733053236-970-width740height495.jpg",
      "https://editorial.pxcrush.net/carsales/general/editorial/isuzu-d-max-x-terrain-2024-tow-17.jpeg?width=1024&height=682"
    ],
    description: "The Isuzu D-MAX X-Terrain combines rugged capability with premium features. Powered by a 3.0L turbo diesel engine delivering 140kW and 450Nm. Top-spec model with leather interior, advanced safety systems, and premium audio.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Leather Interior", "9-inch Touchscreen", "Bose Premium Audio", "360° Camera", "Adaptive Cruise Control", "Wireless Charging", "Apple CarPlay", "Android Auto", "Tow Bar"],
    viewsCount: 156,
    createdAt: new Date("2024-01-10T11:15:00Z"),
    updatedAt: new Date("2024-01-10T11:15:00Z")
  },
  {
    make: "MG",
    model: "ZS EV",
    year: 2024,
    price: 44990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 0,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Arctic White",
    rego: "MGE456",
    vin: "LSJA24U62HG123456",
    stockNumber: "MG24ZSE023",
    images: [
      "https://resource.digitaldealer.com.au/image/12787125536409572473aa6299348707_0_0.jpg",
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/mg/zs-ev/2024/6f0db767-c7f8-577a-b398-7be31df50000",
      "https://editorial.pxcrush.net/carsales/general/editorial/mg-zs-hybrid-plus-15-yhq5.jpg?width=1024&height=682"
    ],
    description: "The MG ZS EV offers an affordable entry into electric vehicle ownership. With a 320km range and rapid charging capability, it's perfect for urban commuting. Modern interior with the latest connectivity features and comprehensive safety systems.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["320km Range", "DC Fast Charging", "10.1-inch Touchscreen", "360° Camera", "Apple CarPlay", "Android Auto", "Wireless Charging", "Leather Interior", "Panoramic Sunroof"],
    viewsCount: 178,
    createdAt: new Date("2024-01-15T14:20:00Z"),
    updatedAt: new Date("2024-01-15T14:20:00Z")
  },
  {
    make: "Skoda",
    model: "Kodiaq RS",
    year: 2023,
    price: 67990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 10.2,
    fuelConsumptionExtraUrban: 7.1,
    fuelConsumptionCombined: 8.3,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 12500,
    driveType: "AWD",
    doors: 5,
    seats: 7,
    color: "Business Grey",
    rego: "SKO789",
    vin: "TMBJJ7NP5P7123456",
    stockNumber: "SK23KOD024",
    images: [
      "https://cdn.yeecar.com.au/uploads/car/spec/S000B2K1.jpg",
      "https://edge.pxcrush.net/dealerweb/car/cil/woh3dnkpjhuc6fhyoa4uac1w4.jpg?width=1000",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKgwSg5kxFfcnX9lU4pULL6Kfrer_jzGtOKw&s"
    ],
    description: "The Skoda Kodiaq RS combines performance with practicality. The 2.0L turbocharged engine produces 180kW, while the seven-seat interior offers family flexibility. RS styling adds sporty touches to this versatile SUV.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["RS Styling", "Virtual Cockpit", "Canton Sound System", "Panoramic Sunroof", "Heated & Ventilated Seats", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Wireless Charging"],
    viewsCount: 145,
    createdAt: new Date("2024-01-20T10:45:00Z"),
    updatedAt: new Date("2024-01-20T10:45:00Z")
  },
  {
    make: "Genesis",
    model: "GV70 3.5T",
    year: 2023,
    price: 84990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 11.5,
    fuelConsumptionExtraUrban: 7.8,
    fuelConsumptionCombined: 9.3,
    engineCapacity: 3.5,
    cylinders: 6,
    odometer: 8500,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Himalayan Grey",
    rego: "GEN012",
    vin: "KM8J3CA46PU123456",
    stockNumber: "GN23GV7025",
    images: [
      "https://media.whichcar.com.au/uploads/2025/05/Genesis-GV70-1-scaled.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLA_7tL-qvNHWRYT0ie-tqhXJC7pBizJOGsQ&s",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2023-Genesis-Electrified-GV70-SUV-Red-JC-1200x800-(11).jpg"
    ],
    description: "The Genesis GV70 3.5T offers luxury and performance in a compact SUV package. The twin-turbo V6 engine delivers 280kW, while the interior showcases premium materials and cutting-edge technology.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Lexicon Premium Audio", "21-inch Alloys", "Nappa Leather", "Head-up Display", "360° Camera", "Remote Smart Parking", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof"],
    viewsCount: 167,
    createdAt: new Date("2024-01-25T13:30:00Z"),
    updatedAt: new Date("2024-01-25T13:30:00Z")
  },
  {
    make: "Suzuki",
    model: "Jimny",
    year: 2024,
    price: 34990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.9,
    fuelConsumptionExtraUrban: 6.4,
    fuelConsumptionCombined: 7.4,
    engineCapacity: 1.5,
    cylinders: 4,
    odometer: 0,
    driveType: "4WD",
    doors: 3,
    seats: 4,
    color: "Jungle Green",
    rego: "SUZ345",
    vin: "JS3TX93V0P4123456",
    stockNumber: "SZ24JIM026",
    images: [
      "https://d2s8i866417m9.cloudfront.net/photo/22512419/photo/medium-ac1a303427e0224f01bcf4f457d5b356.jpg",
      "https://d2s8i866417m9.cloudfront.net/photo/22512437/photo/medium-86281423c35902cde456d5f42a9a1f14.jpg",
      "https://d2s8i866417m9.cloudfront.net/photo/22512451/photo/medium-873c21c2b03f62618d11449a1133eec4.jpg"
    ],
    description: "The Suzuki Jimny combines classic styling with modern features. Its compact size and true 4WD capability make it perfect for urban adventures. Updated interior with the latest connectivity and safety features.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Part-time 4WD", "Hill Descent Control", "9-inch Touchscreen", "Apple CarPlay", "Android Auto", "Cruise Control", "LED Headlights", "Rear View Camera", "Cloth Interior"],
    viewsCount: 234,
    createdAt: new Date("2024-01-30T15:45:00Z"),
    updatedAt: new Date("2024-01-30T15:45:00Z")
  },
  {
    make: "Peugeot",
    model: "3008 GT",
    year: 2023,
    price: 57990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 8.2,
    fuelConsumptionExtraUrban: 5.8,
    fuelConsumptionCombined: 6.8,
    engineCapacity: 1.6,
    cylinders: 4,
    odometer: 15800,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Nera Black",
    rego: "PEU678",
    vin: "VF3YBRHZ8PS123456",
    stockNumber: "PG23PEU027",
    images: [
      "https://cdn.images.stock.i-motor.net.au/vehicles/medium/2840639_P025065_2_384e51590670c41e.jpg",
      "https://www.peugeot.com.au/content/dam/peugeot/australia/models/3008/2024/3008-hybrid/Peugeot-MY24-3008-MHEV-Sprites-1920x1080-GT-Nera-Black-.png",
      "https://editorial.pxcrush.net/carsales/general/editorial/180207_peugeot_3008_09-2q4x.jpg?width=1024&height=682"
    ],
    description: "The Peugeot 3008 GT offers French luxury in a practical SUV package. The 1.6L turbo engine delivers 165kW, while the interior features premium materials and innovative technology.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["GT Styling", "Focal Premium Audio", "12.3-inch Digital Cluster", "10-inch Touchscreen", "Nappa Leather", "Panoramic Sunroof", "Wireless Apple CarPlay", "Android Auto", "360° Camera"],
    viewsCount: 123,
    createdAt: new Date("2024-02-05T11:20:00Z"),
    updatedAt: new Date("2024-02-05T11:20:00Z")
  },
  {
    make: "Cupra",
    model: "Formentor VZ5",
    year: 2023,
    price: 64990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 10.8,
    fuelConsumptionExtraUrban: 7.2,
    fuelConsumptionCombined: 8.7,
    engineCapacity: 2.5,
    cylinders: 5,
    odometer: 9200,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Graphene Grey",
    rego: "CUP901",
    vin: "VSSZZZKMZPS123456",
    stockNumber: "CP23FOR028",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGFuQGFQjARYKedSCLyJ0K5l7s83t2o5G8uw&s",
      "https://images.carexpert.com.au/resize/800/-/cms/v1/media/2023-cupra-formentor-primary-image.jpg",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/cokcwrobiyazjeomucau"
    ],
    description: "The Cupra Formentor VZ5 is a high-performance SUV with a 2.5L turbocharged engine producing 290kW. Its aggressive styling and premium interior make it stand out in the segment.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["VZ5 Styling", "Akrapovic Exhaust", "Brembo Brakes", "12-inch Touchscreen", "Digital Cockpit", "Nappa Leather", "Panoramic Sunroof", "Wireless Apple CarPlay", "Android Auto"],
    viewsCount: 189,
    createdAt: new Date("2024-02-10T14:35:00Z"),
    updatedAt: new Date("2024-02-10T14:35:00Z")
  },
  {
    make: "LDV",
    model: "T60 Max",
    year: 2024,
    price: 42990.00,
    bodyType: "UTE",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 9.5,
    fuelConsumptionExtraUrban: 7.1,
    fuelConsumptionCombined: 8.1,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 0,
    driveType: "4WD",
    doors: 4,
    seats: 5,
    color: "Galaxy Blue",
    rego: "LDV234",
    vin: "LSJA24U62HG123456",
    stockNumber: "LD24T60029",
    images: [
      "https://resource.digitaldealer.com.au/image/7092859067da6a96129a6167121987_0_0.jpg",
      "https://cdn.images.stock.i-motor.net.au/vehicles/large/2966900-D94229-f1e2589a-5a3e-576c-a411-edcb08dcde57.jpg",
      "https://editorial.pxcrush.net/carsales/general/editorial/2024-ldv-t60-040.jpg?width=1024&height=682"
    ],
    description: "The LDV T60 Max offers exceptional value in the dual-cab ute segment. With a 2.0L turbo diesel engine and comprehensive features, it's perfect for both work and family use.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Leather Interior", "10-inch Touchscreen", "360° Camera", "Apple CarPlay", "Android Auto", "Wireless Charging", "LED Headlights", "Tow Bar", "Tub Liner"],
    viewsCount: 145,
    createdAt: new Date("2024-02-15T09:50:00Z"),
    updatedAt: new Date("2024-02-15T09:50:00Z")
  },
  {
    make: "GWM",
    model: "Haval H6 Ultra",
    year: 2024,
    price: 39990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.2,
    fuelConsumptionExtraUrban: 6.8,
    fuelConsumptionCombined: 7.8,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 0,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Nova White",
    rego: "GWM567",
    vin: "LGWEF4A53PH123456",
    stockNumber: "GW24H6U030",
    images: [
      "https://resource.digitaldealer.com.au/image/45637030265d6b59c14e26657168674_0_0.jpg",
      "https://d2s8i866417m9.cloudfront.net/photo/20306291/photo/medium-73cf9c0dc5043842c55ea812bea8139d.jpg",
      "https://cdn.images.stock.i-motor.net.au/vehicles/large/3278919-H2502-015-7d21bc8a-f899-5088-9cbe-0d1ffe03e7ed.jpg"
    ],
    description: "The GWM Haval H6 Ultra offers premium features at an affordable price. The 2.0L turbo engine delivers 150kW, while the interior features premium materials and advanced technology.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Leather Interior", "12.3-inch Touchscreen", "Panoramic Sunroof", "360° Camera", "Wireless Charging", "Apple CarPlay", "Android Auto", "LED Headlights", "Power Tailgate"],
    viewsCount: 167,
    createdAt: new Date("2024-02-20T13:25:00Z"),
    updatedAt: new Date("2024-02-20T13:25:00Z")
  },
  {
    make: "Volvo",
    model: "XC60 Recharge",
    year: 2024,
    price: 84990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PLUGIN_HYBRID",
    fuelConsumptionUrban: 2.1,
    fuelConsumptionExtraUrban: 2.3,
    fuelConsumptionCombined: 2.2,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 0,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Crystal White",
    rego: "VOL123",
    vin: "YV1LFA0ACR1234567",
    stockNumber: "VO24XC6031",
    images: [
      "https://vehicle-images.dealerinspire.com/8748-110009017/YV4H60DM4R1755428/02b606b25dbb4365252c5f2b6f21ef1c.jpg",
      "https://www.begadistrictnews.com.au/images/transform/v1/crop/frm/silverstone-feed-data/0d5d528f-be4a-4444-a3d3-a51e0f95bb90.jpg/r0_0_800_533_w800_h533_fmax.jpg",
      "https://www.volvocars.com/images/cs/v3/assets/blt0feaa88e629251fc/blt8a150026c2d8be09/669014e0b71f97b6c0a7c5ce/xc60-fuel-single-media-callout-4x3.jpg?branch=prod_alias&auto=avif&quality=85&format=webp&iar=0&w=3840&imdensity=1"
    ],
    description: "The Volvo XC60 Recharge combines luxury with sustainability. This plug-in hybrid offers 455kW combined power with an electric range of 77km. Premium interior with sustainable materials and advanced safety features.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Bowers & Wilkins Audio", "Air Suspension", "Nappa Leather", "Pilot Assist", "360° Camera", "Wireless Charging", "Apple CarPlay", "Android Auto", "Panoramic Sunroof"],
    viewsCount: 145,
    createdAt: new Date("2024-02-25T10:15:00Z"),
    updatedAt: new Date("2024-02-25T10:15:00Z")
  },
  {
    make: "Porsche",
    model: "Taycan 4S",
    year: 2023,
    price: 149990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 8500,
    driveType: "AWD",
    doors: 4,
    seats: 4,
    color: "Miami Blue",
    rego: "POR456",
    vin: "WP0AA2Y1XPS123456",
    stockNumber: "PO23TAY032",
    images: [
      "https://static0.carbuzzimages.com/wordpress/wp-content/uploads/2024/02/14202-14.jpg",
      "https://vehicle-images.dealerinspire.com/57f5-110010808/thumbnails/large/WP0AB2Y14SSA42088/c3ccd6a8338e4705d956d9decf729573.jpg",
      "https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_690x388/dam/pnr/2024/Products/The-new-Taycan/Taycan_Turbo_Cross_Turismo_interior_6.jpg/jcr:content/Taycan_Turbo_Cross_Turismo_interior_6.jpg"
    ],
    description: "The Porsche Taycan 4S delivers sports car performance with zero emissions. Dual electric motors produce 360kW, enabling 0-100km/h in 4.0 seconds. Premium interior with Porsche's latest technology and charging capabilities.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Performance Battery Plus", "Sport Chrono", "Bose Sound System", "Panoramic Roof", "Adaptive Air Suspension", "Porsche Torque Vectoring", "Wireless Apple CarPlay", "Android Auto", "Heated & Ventilated Seats"],
    viewsCount: 289,
    createdAt: new Date("2024-03-01T14:30:00Z"),
    updatedAt: new Date("2024-03-01T14:30:00Z")
  },
  {
    make: "Subaru",
    model: "Outback Touring",
    year: 2024,
    price: 49990.00,
    bodyType: "WAGON",
    transmission: "CVT",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.2,
    fuelConsumptionExtraUrban: 6.8,
    fuelConsumptionCombined: 7.8,
    engineCapacity: 2.5,
    cylinders: 4,
    odometer: 0,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Autumn Green",
    rego: "SUB789",
    vin: "JF1BS6A67RH123456",
    stockNumber: "SB24OUT033",
    images: [
      "https://pictures.dealer.com/s/soa/1380/892c2c8efb682cba98075d4cd375763ex.jpg?impolicy=downsize&h=674",
      "https://cdn.images.stock.i-motor.net.au/vehicles/medium/3241525-SU067814A-d0b286b3-22df-5822-a72a-6f687a70f84d.jpg",
      "https://editorial.pxcrush.net/carsales/general/editorial/2024-subaru-outback-14.jpg?width=1024&height=682"
    ],
    description: "The Subaru Outback Touring combines wagon practicality with SUV capability. Symmetrical AWD and X-Mode provide all-terrain confidence, while the premium interior offers comfort and technology for long journeys.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Nappa Leather", "Harman/Kardon Audio", "11.6-inch Touchscreen", "EyeSight Driver Assist", "Panoramic Sunroof", "Power Tailgate", "Wireless Apple CarPlay", "Android Auto", "Heated & Ventilated Seats"],
    viewsCount: 167,
    createdAt: new Date("2024-03-05T11:45:00Z"),
    updatedAt: new Date("2024-03-05T11:45:00Z")
  },
  {
    make: "Alfa Romeo",
    model: "Giulia Quadrifoglio",
    year: 2023,
    price: 139990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 14.5,
    fuelConsumptionExtraUrban: 7.8,
    fuelConsumptionCombined: 10.5,
    engineCapacity: 2.9,
    cylinders: 6,
    odometer: 12500,
    driveType: "RWD",
    doors: 4,
    seats: 5,
    color: "Rosso Competizione",
    rego: "ALF012",
    vin: "ZAREA4BB0P7123456",
    stockNumber: "AR23GIU034",
    images: [
      "https://di-uploads-pod5.dealerinspire.com/arrigoalfaromeoofwestpalm/uploads/2023/07/Rosso-Red-Etna.png",
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/alfa-romeo/giulia/2023/5a6a5276-67a8-5e38-b37a-8f3cba150000",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2023-Alfa-Romeo-Giulia-Quadrifoglio-Red-1200x800-(11).jpg"
    ],
    description: "The Alfa Romeo Giulia Quadrifoglio is a high-performance sedan with a Ferrari-derived 2.9L twin-turbo V6 producing 375kW. Carbon fiber components and race-inspired interior create an authentic Italian sports car experience.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Carbon Fiber Hood", "Carbon Ceramic Brakes", "Sparco Sports Seats", "Harman/Kardon Audio", "Adaptive Suspension", "Torque Vectoring", "Apple CarPlay", "Android Auto", "Wireless Charging"],
    viewsCount: 234,
    createdAt: new Date("2024-03-10T15:20:00Z"),
    updatedAt: new Date("2024-03-10T15:20:00Z")
  },
  {
    make: "Kia",
    model: "EV6 GT",
    year: 2024,
    price: 94990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 0,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Yacht Blue",
    rego: "KIA345",
    vin: "KNAJZ4AC8P5123456",
    stockNumber: "KI24EV6035",
    images: [
      "https://www.motortrend.com/uploads/2023/10/2024-Kia-EV6-GT-2-front-view.jpg?w=768&width=768&q=75&format=webp",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkFEON6WGNmtSatpWDNDtvn_VXXd62lsGEUQ&s",
      "https://editorial.pxcrush.net/carsales/general/editorial/kia-ev6-gt-line-awd-23-d3pb.jpg?width=1024&height=682"
    ],
    description: "The Kia EV6 GT is a high-performance electric SUV with 430kW of power. 0-100km/h in 3.5 seconds with a range of 424km. Premium interior with advanced technology and rapid charging capability.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["GT Mode", "21-inch Alloys", "Meridian Audio", "Augmented Reality HUD", "Panoramic Sunroof", "Heated & Ventilated Seats", "Wireless Apple CarPlay", "Android Auto", "V2L Power Supply"],
    viewsCount: 198,
    createdAt: new Date("2024-03-15T09:35:00Z"),
    updatedAt: new Date("2024-03-15T09:35:00Z")
  },
  {
    make: "Mercedes-Benz",
    model: "E-Class Wagon",
    year: 2023,
    price: 119990.00,
    bodyType: "WAGON",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 10.2,
    fuelConsumptionExtraUrban: 6.8,
    fuelConsumptionCombined: 8.2,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 15800,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Obsidian Black",
    rego: "MBE678",
    vin: "W213S4EB3PX123456",
    stockNumber: "MB23ECW036",
    images: [
      "https://alcf.s3.us-west-1.amazonaws.com/_custom/2023/mercedes-benz/e-class-wagon/2023%20Mercedes-Benz%20AMG%C2%AE%20E%2063%20S%20Wagon.png",
      "https://hips.hearstapps.com/hmg-prod/images/2021-genesis-g80-3p5t-prestige-v-2021-mercedes-benz-e450-sedan-1768-edit-1621887031.jpg?crop=0.454xw:0.378xh;0.171xw,0.540xh&resize=1200:*",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCVPdqALzeHAdqYknMv5MMjZVs2Og3IK5W_Q&s"
    ],
    description: "The Mercedes-Benz E-Class Wagon combines luxury with practicality. The 3.0L inline-6 engine delivers 270kW, while the interior offers premium comfort and advanced technology. Perfect for long-distance travel with ample cargo space.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Air Suspension", "Burmester Sound", "Panoramic Sunroof", "Nappa Leather", "Head-up Display", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Power Tailgate"],
    viewsCount: 156,
    createdAt: new Date("2024-03-20T13:50:00Z"),
    updatedAt: new Date("2024-03-20T13:50:00Z")
  },
  {
    make: "Polestar",
    model: "2 Long Range",
    year: 2024,
    price: 64990.00,
    bodyType: "HATCHBACK",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 0,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Thunder Grey",
    rego: "POL901",
    vin: "LVVDB40B8P5123456",
    stockNumber: "PS24POL037",
    images: [
      "https://ik.imagekit.io/vyro/public/autofox-api-mapped-to-vehicles/482b9073cbb3dd5c7a23d33745662b10f3514fc44ac1dfe4e61b913439e8dfcc.jpg?tr=f-auto%2Cw-760",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/f79e223d-8a38-5faa-9558-27bfae850000",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/dyrxdmciytclsfxnscrr"
    ],
    description: "The Polestar 2 Long Range offers premium electric mobility with a range of 540km. Dual electric motors produce 300kW, while the minimalist interior showcases sustainable materials and Google's Android Automotive OS.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Google Built-in", "Harman/Kardon Audio", "Panoramic Glass Roof", "Vegan Interior", "Pilot Assist", "360° Camera", "Wireless Charging", "Heat Pump", "Power Tailgate"],
    viewsCount: 178,
    createdAt: new Date("2024-03-25T10:25:00Z"),
    updatedAt: new Date("2024-03-25T10:25:00Z")
  },
  {
    make: "Audi",
    model: "RS6 Avant",
    year: 2023,
    price: 179990.00,
    bodyType: "WAGON",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 14.5,
    fuelConsumptionExtraUrban: 8.2,
    fuelConsumptionCombined: 10.8,
    engineCapacity: 4.0,
    cylinders: 8,
    odometer: 9200,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Nardo Grey",
    rego: "AUD234",
    vin: "WAUZZZF49MN123456",
    stockNumber: "AU23RS6038",
    images: [
      "https://i.ytimg.com/vi/5s1LvKGNdw8/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAm6Oph2fXDp9Ru_ltOG__dzvchBQ",
      "https://www.saxton4x4.co.uk/uploads/images/vehicles/large/1742661847HR-WUAZZZF25PN904419-RE23FOA-02.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/2021-audi-rs6-avant-119-1605052190.jpg?crop=1xw:0.9166666666666666xh;center,top&resize=980:*"
    ],
    description: "The Audi RS6 Avant is the ultimate performance wagon. The 4.0L twin-turbo V8 produces 441kW, while the interior combines luxury with practicality. Perfect for those who want supercar performance with family versatility.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["RS Sport Suspension", "Bang & Olufsen 3D Sound", "Carbon Ceramic Brakes", "RS Sport Seats", "Virtual Cockpit", "Head-up Display", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof"],
    viewsCount: 267,
    createdAt: new Date("2024-03-30T14:40:00Z"),
    updatedAt: new Date("2024-03-30T14:40:00Z")
  },
  {
    make: "BYD",
    model: "Atto 3",
    year: 2024,
    price: 44990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 0,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Surf Blue",
    rego: "BYD567",
    vin: "LSJA24U62HG123456",
    stockNumber: "BY24ATT039",
    images: [
      "https://www.topgear.com/sites/default/files/2023/03/25-BYD-Atto-3.jpg",
      "https://carsguide-res.cloudinary.com/image/upload/e_trim:10,f_auto/c_scale,t_cg_base,w_678/v1/editorial/2022-BYD-Atto-3.png",
      "https://editorial.pxcrush.net/carsales/general/editorial/byd-atto-3-09-7uo2.jpg?width=1024&height=682"
    ],
    description: "The BYD Atto 3 offers an affordable entry into electric vehicle ownership. With a 420km range and rapid charging capability, it's perfect for urban commuting. Modern interior with rotating touchscreen and comprehensive safety features.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Rotating Touchscreen", "360° Camera", "Panoramic Sunroof", "Vegan Leather", "Heat Pump", "Wireless Charging", "Apple CarPlay", "Android Auto", "Power Tailgate"],
    viewsCount: 145,
    createdAt: new Date("2024-04-05T11:15:00Z"),
    updatedAt: new Date("2024-04-05T11:15:00Z")
  },
  {
    make: "Jaguar",
    model: "F-Pace SVR",
    year: 2023,
    price: 139990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 15.2,
    fuelConsumptionExtraUrban: 8.5,
    fuelConsumptionCombined: 11.2,
    engineCapacity: 5.0,
    cylinders: 8,
    odometer: 15800,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Caldera Red",
    rego: "JAG890",
    vin: "SALWA2VF8PA123456",
    stockNumber: "JG23FPS040",
    images: [
      "https://www.exoticcarhacks.com/wp-content/uploads/2025/01/Used-2020-Jaguar-F-PACE-SVR-in-Firenze-Red-w-Drive-Pack-Lux-Pack-Meridian-Sound-1722892010.jpg",
      "https://www.topgear.com/sites/default/files/2022/07/DSC08792.jpg",
      "https://carsguide-res.cloudinary.com/image/upload/c_fit,h_841,w_1490,f_auto,t_cg_base/v1/editorial/2021-Jaguar-F-PACE-R-Dynamic-SE-P400%20-Eiger-Grey-press-image-1200x800p-(22).jpg"
    ],
    description: "The Jaguar F-Pace SVR is a high-performance SUV with a 5.0L supercharged V8 producing 405kW. Dynamic handling with adaptive suspension and quad exhaust system. Premium interior with performance seats and advanced technology.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["SVR Styling", "Meridian Sound", "Adaptive Dynamics", "Performance Seats", "Head-up Display", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof"],
    viewsCount: 189,
    createdAt: new Date("2024-04-10T15:30:00Z"),
    updatedAt: new Date("2024-04-10T15:30:00Z")
  },
  {
    make: "Lexus",
    model: "LC 500",
    year: 2023,
    price: 179990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 14.5,
    fuelConsumptionExtraUrban: 7.8,
    fuelConsumptionCombined: 10.5,
    engineCapacity: 5.0,
    cylinders: 8,
    odometer: 12500,
    driveType: "RWD",
    doors: 2,
    seats: 4,
    color: "Structural Blue",
    rego: "LEX123",
    vin: "JTHHZ1BA8P5123456",
    stockNumber: "LX23LC5041",
    images: [
      "https://media.drive.com.au/obj/tx_rs:auto:2000:1125:1/caradvice/private/4954a7d94130ae22ca0627e536689c13",
      "https://images.carexpert.com.au/resize/800/-/cms/v1/media/2024-lexus-lc-primary-image.jpg",
      "https://2684054.fs1.hubspotusercontent-na1.net/hub/2684054/hubfs/2024-Lexus-LC500-convertible-interior-2-carpro.jpg?width=1200&length=1200&name=2024-Lexus-LC500-convertible-interior-2-carpro.jpg"
    ],
    description: "The Lexus LC 500 is a grand tourer with a naturally aspirated 5.0L V8 producing 351kW. Stunning design with premium materials and advanced technology. Perfect for those seeking a unique luxury sports car experience.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Mark Levinson Audio", "Carbon Roof", "Adaptive Variable Suspension", "Limited Slip Differential", "Head-up Display", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Panoramic Glass Roof"],
    viewsCount: 234,
    createdAt: new Date("2024-04-15T09:45:00Z"),
    updatedAt: new Date("2024-04-15T09:45:00Z")
  },
  {
    make: "Renault",
    model: "Megane E-Tech",
    year: 2024,
    price: 49990.00,
    bodyType: "HATCHBACK",
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    fuelConsumptionUrban: null,
    fuelConsumptionExtraUrban: null,
    fuelConsumptionCombined: null,
    engineCapacity: null,
    cylinders: null,
    odometer: 0,
    driveType: "FWD",
    doors: 5,
    seats: 5,
    color: "Flame Red",
    rego: "REN456",
    vin: "VF1RFE0B0PS123456",
    stockNumber: "RN24MEG042",
    images: [
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/skdiprulertinmrus3n1",
      "https://media.drive.com.au/obj/tx_rs:auto:3483:1959:1/driveau/upload/cms/uploads/apqm91vt235juhoo6kkl",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/exxug4fiivf5xny9obxa"
    ],
    description: "The Renault Megane E-Tech offers French design with electric performance. 160kW electric motor with a 450km range. Modern interior with Google built-in and comprehensive safety features.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Google Built-in", "12.3-inch Display", "OpenR Link", "360° Camera", "Panoramic Sunroof", "Wireless Charging", "Apple CarPlay", "Android Auto", "Power Tailgate"],
    viewsCount: 167,
    createdAt: new Date("2024-04-20T13:20:00Z"),
    updatedAt: new Date("2024-04-20T13:20:00Z")
  },
  {
    make: "Maserati",
    model: "Grecale Trofeo",
    year: 2023,
    price: 159990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 15.8,
    fuelConsumptionExtraUrban: 8.9,
    fuelConsumptionCombined: 11.8,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 15800,
    driveType: "AWD",
    doors: 5,
    seats: 5,
    color: "Bianco Audace",
    rego: "MAS789",
    vin: "ZAM57BLA0P7123456",
    stockNumber: "MS23GRE043",
    images: [
      "https://media.drive.com.au/obj/tx_q:70,rs:auto:960:540:1/driveau/upload/vehicles/used/maserati/grecale/2023/cfca0f70-4627-5627-986d-42fb37b50000",
      "https://cdn.images.stock.i-motor.net.au/vehicles/medium/42b77e45-f830-4fdd-bd23-e23849df7b00-0-carsales097.jpg",
      "https://images.carexpert.com.au/resize/3000/-/app/uploads/2023/06/2023-Maserati-Grecale-GT-32.jpg"
    ],
    description: "The Maserati Grecale Trofeo is a high-performance SUV with a 3.0L twin-turbo V6 producing 390kW. Italian luxury with advanced technology and dynamic handling. Perfect for those seeking exclusivity and performance.",
    status: "AVAILABLE",
    condition: "USED",
    features: ["Sonus Faber Audio", "Air Suspension", "MIA System", "Head-up Display", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof", "Heated & Ventilated Seats"],
    viewsCount: 198,
    createdAt: new Date("2024-04-25T10:35:00Z"),
    updatedAt: new Date("2024-04-25T10:35:00Z")
  },
  {
    make: "Mini",
    model: "John Cooper Works",
    year: 2024,
    price: 59990.00,
    bodyType: "HATCHBACK",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 9.8,
    fuelConsumptionExtraUrban: 6.2,
    fuelConsumptionCombined: 7.7,
    engineCapacity: 2.0,
    cylinders: 4,
    odometer: 0,
    driveType: "FWD",
    doors: 3,
    seats: 4,
    color: "Chili Red",
    rego: "MIN012",
    vin: "WMWZY7C05P5123456",
    stockNumber: "MN24JCW044",
    images: [
      "https://carsales.pxcrush.net/general/car/spec/S0008IFB.jpg?width=618&height=412&watermark=502663494",
      "https://cdn.yeecar.com.au/uploads/car/spec/S000CRHI.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/2022-mini-jcw-convertible-871-1635861250.jpg"
    ],
    description: "The Mini John Cooper Works is a high-performance hot hatch with a 2.0L turbo engine producing 225kW. Go-kart handling with premium interior and advanced technology. Perfect for those seeking fun and practicality.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["JCW Styling", "Harman/Kardon Audio", "Head-up Display", "Adaptive Suspension", "LED Headlights", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof", "Heated Sports Seats"],
    viewsCount: 178,
    createdAt: new Date("2024-04-30T14:50:00Z"),
    updatedAt: new Date("2024-04-30T14:50:00Z")
  },
  {
    make: "Land Rover",
    model: "Defender 110",
    year: 2024,
    price: 139990.00,
    bodyType: "SUV",
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    fuelConsumptionUrban: 11.2,
    fuelConsumptionExtraUrban: 8.5,
    fuelConsumptionCombined: 9.6,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 0,
    driveType: "4WD",
    doors: 5,
    seats: 7,
    color: "Pangea Green",
    rego: "LRD345",
    vin: "SALWA2VF8PA123456",
    stockNumber: "LR24DEF045",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTozCmFL1TCAnhnkCRW2zkBzq62n75JdtIPkg&s",
      "https://robbreport.com.au/application/assets/2022/09/03_DEF_23-5MY_75TH_EDITION_110_140922.jpg",
      "https://di-uploads-pod12.dealerinspire.com/landroverlouisville/uploads/2022/09/Land-Rover-Defender-110-Technology-2209.jpg"
    ],
    description: "The Land Rover Defender 110 combines legendary off-road capability with modern luxury. The 3.0L diesel engine delivers 221kW, while the interior offers premium comfort and advanced technology. Perfect for adventure and daily use.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Terrain Response 2", "Air Suspension", "Meridian Audio", "ClearSight Ground View", "360° Camera", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof", "Heated & Ventilated Seats"],
    viewsCount: 245,
    createdAt: new Date("2024-05-05T11:25:00Z"),
    updatedAt: new Date("2024-05-05T11:25:00Z")
  },
  {
    make: "Bentley",
    model: "Continental GT",
    year: 2023,
    price: 379990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 18.5,
    fuelConsumptionExtraUrban: 9.2,
    fuelConsumptionCombined: 13.1,
    engineCapacity: 4.0,
    cylinders: 8,
    odometer: 8500,
    driveType: "AWD",
    doors: 2,
    seats: 4,
    color: "Beluga Black",
    rego: "BEN678",
    vin: "SCBLC37F8PC123456",
    stockNumber: "BN23CON046",
    images: [
      "https://nextgen-cella.cdn.dealersolutions.com.au/20241205/a1c137c41c592f6c59698db2e99f8378.jpg",
      "https://edge.pxcrush.net/cars/dealer/bmefw53jtjiomfcouytzosye6.jpg?pxc_expires=20250722161721&pxc_clear=1&pxc_signature=b2bd2a04daa814a75f7a87ef5d555c9d&pxc_size=1795%2C1197&pxc_method=fit",
      "https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/t7xkapqz28ymmmqogaug"
    ],
    description: "The Bentley Continental GT is the ultimate grand tourer. The 4.0L twin-turbo V8 produces 404kW, while the interior showcases handcrafted luxury and cutting-edge technology. Perfect for those seeking the pinnacle of automotive luxury.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Naim Audio", "Rotating Display", "Diamond Knurling", "City Specification", "Tour Specification", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof", "Heated & Ventilated Seats"],
    viewsCount: 289,
    createdAt: new Date("2024-05-10T15:40:00Z"),
    updatedAt: new Date("2024-05-10T15:40:00Z")
  },
  {
    make: "Ferrari",
    model: "296 GTB",
    year: 2023,
    price: 579990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PLUGIN_HYBRID",
    fuelConsumptionUrban: 8.5,
    fuelConsumptionExtraUrban: 6.2,
    fuelConsumptionCombined: 7.2,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 5800,
    driveType: "RWD",
    doors: 2,
    seats: 2,
    color: "Rosso Corsa",
    rego: "FER901",
    vin: "ZFF98NLA0P0123456",
    stockNumber: "FR23GTB047",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvaMxfSOTyoRa38sDpWB9IG6kU8iK_7S1e1A&s",
      "https://carsales.pxcrush.net/carsales/cars/dealer/60qgo15fg8pvwfiu4vgssvo1r.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900,600",
      "https://dealersolutions.b-cdn.net/20241217/8ac409b91f9654cfa7f38ab9bb1011c7.jpg"
    ],
    description: "The Ferrari 296 GTB is a revolutionary hybrid supercar. The 3.0L V6 with electric motor produces 610kW, while the design showcases Ferrari's latest aerodynamic technology. Perfect for those seeking the ultimate driving experience.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Assetto Fiorano", "Carbon Fiber Wheels", "Carbon Ceramic Brakes", "Manettino", "RAC-e", "Apple CarPlay", "Android Auto", "Telemetry", "Track Display"],
    viewsCount: 345,
    createdAt: new Date("2024-05-15T09:55:00Z"),
    updatedAt: new Date("2024-05-15T09:55:00Z")
  },
  {
    make: "Lamborghini",
    model: "Huracan EVO",
    year: 2023,
    price: 479990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 19.5,
    fuelConsumptionExtraUrban: 10.2,
    fuelConsumptionCombined: 14.1,
    engineCapacity: 5.2,
    cylinders: 10,
    odometer: 4200,
    driveType: "AWD",
    doors: 2,
    seats: 2,
    color: "Verde Mantis",
    rego: "LAM234",
    vin: "ZHWUF4ZD8PLA12345",
    stockNumber: "LB23HUR048",
    images: [
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/c51905b0000b639a185eeb080dd879bf007f5604/photos/3yX52g5M-SGUi4PJSTM-(edit).jpg?t=172674684446",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShf3TIxyYrjKmJJ7KIdhFuV0Vvk9bDkh4LxQ&s",
      "https://www.lamborghinigoldcoast.com/imagetag/10443/10/l/New-2023-Lamborghini-huracan-Evo-1668808574.jpg"
    ],
    description: "The Lamborghini Huracan EVO is a mid-engine supercar with a 5.2L V10 producing 470kW. Advanced aerodynamics and dynamic handling make it a track-focused machine. Perfect for those seeking raw performance and Italian passion.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["ANIMA System", "Carbon Ceramic Brakes", "Forged Wheels", "Lifting System", "Telemetry", "Apple CarPlay", "Android Auto", "Carbon Fiber Interior", "Sport Seats"],
    viewsCount: 378,
    createdAt: new Date("2024-05-20T13:30:00Z"),
    updatedAt: new Date("2024-05-20T13:30:00Z")
  },
  {
    make: "McLaren",
    model: "Artura",
    year: 2024,
    price: 429990.00,
    bodyType: "COUPE",
    transmission: "AUTOMATIC",
    fuelType: "PLUGIN_HYBRID",
    fuelConsumptionUrban: 8.9,
    fuelConsumptionExtraUrban: 6.2,
    fuelConsumptionCombined: 7.4,
    engineCapacity: 3.0,
    cylinders: 6,
    odometer: 0,
    driveType: "RWD",
    doors: 2,
    seats: 2,
    color: "Papaya Orange",
    rego: "MCL567",
    vin: "SBM12DAA8MW123456",
    stockNumber: "MC24ART049",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6vKTUhXn0eMegN_Xx4LUQfttsvG67nem_zg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQxJLzKhXM4n-LpaqLjX7xfmJlxcz9qP7EXQ&s",
      "https://evcentral.com.au/wp-content/uploads/2024/06/McLaren-interior.webp"
    ],
    description: "The McLaren Artura is a revolutionary hybrid supercar. The 3.0L V6 with electric motor produces 500kW, while the carbon fiber architecture ensures lightweight performance. Perfect for those seeking cutting-edge technology and track capability.",
    status: "AVAILABLE",
    condition: "NEW",
    features: ["Variable Drift Control", "Carbon Ceramic Brakes", "Track Telemetry", "Variable Drift Control", "Track Telemetry", "Apple CarPlay", "Android Auto", "Carbon Fiber Seats", "Track Display"],
    viewsCount: 312,
    createdAt: new Date("2024-05-25T10:45:00Z"),
    updatedAt: new Date("2024-05-25T10:45:00Z")
  },
  {
    make: "Rolls-Royce",
    model: "Ghost",
    year: 2023,
    price: 679990.00,
    bodyType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    fuelConsumptionUrban: 19.5,
    fuelConsumptionExtraUrban: 10.2,
    fuelConsumptionCombined: 14.1,
    engineCapacity: 6.75,
    cylinders: 12,
    odometer: 5800,
    driveType: "RWD",
    doors: 4,
    seats: 5,
    color: "Diamond Black",
    rego: "ROR890",
    vin: "SCA681S51PUX12345",
    stockNumber: "RR23GHO050",
    images: [
      "https://www.motortrend.com/uploads/2023/04/2023-Rolls-Royce-Ghost-Black-Badge-exterior-2.jpg",
      "https://i.ytimg.com/vi/H8bMdbX8jss/maxresdefault.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/2023-rolls-royce-black-badge-103-1673365007.jpeg?crop=1xw:0.8441807044410413xh;center,top&resize=1200:*"
    ],
    description: "The Rolls-Royce Ghost is the ultimate luxury sedan. The 6.75L V12 produces 420kW, while the interior showcases handcrafted luxury and cutting-edge technology. Perfect for those seeking the pinnacle of automotive luxury.",
    status: "AVAILABLE",
    condition: "CERTIFIED",
    features: ["Bespoke Audio", "Starlight Doors", "Planar Suspension", "Spirit of Ecstasy", "Wireless Apple CarPlay", "Android Auto", "Panoramic Sunroof", "Heated & Ventilated Seats", "Bespoke Clock"],
    viewsCount: 289,
    createdAt: new Date("2024-05-30T14:55:00Z"),
    updatedAt: new Date("2024-05-30T14:55:00Z")
  }
]


